### ISSUE TITLE
Git clone does not work properly

### ISSUE THREAD

**Issue by eihqnh** [radumamy/Termux-openSUSE#1]
Hello, when I tried some projects of GIT clone. Git / config reported an error.
This seems to be a bug?

```
 localhost:~ # git clone https://github.com/neovim/neovim
Cloning into 'neovim'...
warning: unable to access '/root/neovim/.git/config': Operation not permitted
fatal: unknown error occurred while reading the configuration files
```

**Comment by radumamy** [comment]
Hi @eihqnh. What version of openSUSE, Termux and Android are you using? Thank you.

**Comment by radumamy** [comment]
@eihqnh. This has been resolved in the latest version of Proot. Please update it.
