### ISSUE TITLE
git clone “.git/config: Operation not permitted”

### ISSUE THREAD

**Issue by eihqnh** [radumamy/Termux-openSUSE#2]
localhost:~ # git clone https://github.com/termux/termux-app
Cloning into 'termux-app'...
warning: unable to access '/root/termux-app/.git/config': Operation not permitted
fatal: unknown error occurred while reading the configuration files

It is a bug？

**Comment by radumamy** [comment]
Just tested it, it works fine. Please update Proot in Termux

**Comment by eihqnh** [comment]
@radumamy  I'm sorry for my carelessness.Thank you very much
